### ISSUE TITLE
Get an error during installation.

### ISSUE THREAD

**Issue by TheComposingStick** [aklaswad/mt-plugin-oauth-framework#3]
MT-4.34

After copying plugin to plugin directory I log in and received a notice that the plugin needs to be upgraded. I click on begin upgrade and get the following error.

Can't use an undefined value as a HASH reference 

Rob

**Comment by aklaswad** [comment]
Hi Rob
It's because Net::OAuth module which bundled with MT4.x is a bit old.
I bundled the latest version into plugin's extlib, and it works for me now. please try the latest source. thanks!
