### ISSUE TITLE
A few more problems running under MT4.x

### ISSUE THREAD

**Issue by TheComposingStick** [aklaswad/mt-plugin-oauth-framework#4]
Thank you for your previous reply. The update fixed the installation error.

Am I correct in thinking this was written for MT5?

I am have a few more problems.

1) The menus do not appear, I think this is because in MT4 the menu is preferences but in MT5 it is settings.

2) When I manually construct the url with __mode=list_oauth_providers I get the error
Can't locate object method &quot;can_do&quot; via package &quot;MT::App::CMS&quot; at C:\Athena\mt\plugins\OAuthFramework\lib/MT/CMS/OAuth.pm line 8. Looking through the MT docs can_do seems to be part of the MT5 permissions lib.

**Comment by aklaswad** [comment]
Yes, now this plugin was tested only on MT5, but I would like to run it with both MT4 and MT5.
Now I started working for it, so please wait a few more hours...

**Comment by aklaswad** [comment]
I got pushed fixed codes for those MT4 problems above.
and continuing more test for MT4. it's nice Saturday evening.

anyway, thank you Rob for your reports!

**Comment by aklaswad** [comment]
I also found lib-www-perl package which bundled with MT4.3x is very aged. please see updated README.pod.

**Comment by TheComposingStick** [comment]
Thank you.
I have now been able to get this working with MT4. Next step is to update my plugin to connect via OAuth.
